swagger: '2.0'
info:
  title: publish
  description: API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /weather1NEED TO FILL!!!:
  get:
    summary: get what results we get NEED TO FILL!!!
    operationId: NEED TO FILL
    x-google-backend:
      address: https://us-central1-week9-1-323806.cloudfunctions.net/NEEDTOFILL!!!
  /weather2NEED TO FILL!!!:
  get:
    summary: get what results we get NEED TO FILL!!!
    operationId: NEED TO FILL
    x-google-backend:
      address: https://us-central1-week9-1-323806.cloudfunctions.net/NEEDTOFILL!!!
