swagger: '2.0'
info:
  title: publish
  description: API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /index-rain:
  get:
    summary: json with index to rain amounts
    operationId: index-rain
    x-google-backend:
      address: https://us-central1-week9-1-323806.cloudfunctions.net/NEEDTOFILL!!!
  /index-temperature:
  get:
    summary: json with index to max temperature
    operationId: index-maxtemperature
    x-google-backend:
      address: https://us-central1-week9-1-323806.cloudfunctions.net/NEEDTOFILL!!!
